version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: learn
    

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL= test@test.com
      PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "80:80"
